name_model = "Qwen/Qwen2.5-Coder-0.5B"
num_gpus = 1
sample_per_file = 8

[data]
max_samples = 8
batch_size = 8
path = "PrimeIntellect/verifiable-tasks"

# sampling parameters
temperature = 0.6 # 0.6 is the value from the R1 model card for evaluation
